[workspace]
resolver = "2"
members = ["core", "bindings"]

[workspace.package]
version = "0.1.0"
rust-version = "1.85"
edition = "2024"
license = "GPL-3.0-only"
authors = [""]

[workspace.dependencies]
anyhow = { version = "1.0.95" }
bincode = { version = "1.3.3" }
ethers-contract = { version = "2.0.14" }
ethers-core = { version = "2.0.14" }
ethers-providers = { version = "2.0.14" }
revm = { version = "19.4.0", features = ["ethersdb", "serde", "serde-json"] }
alloy-sol-types = { version = "=0.8.19", default-features = false, features = [
    "std",
] }
alloy-primitives = { version = "=0.8.19", default-features = false, features = [
    "rlp",
    "map",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = { version = "1.0" }
tokio = { version = "1.43.0" }

[profile.release]
lto = true
strip = "symbols"
