name: CI

on: pull_request

permissions:
    pull-requests: write
    contents: read

jobs:
    check-commits:
        runs-on: ubuntu-latest
        steps:
            - name: Check number of commits in PR
              id: commits
              uses: actions/github-script@v6
              with:
                  script: |
                      const pr = context.payload.pull_request;
                      const commits = await github.rest.pulls.listCommits({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.number,
                      });
                      core.setOutput("count", commits.data.length);
                      core.setOutput("from_fork", pr.head.repo.full_name !== pr.base.repo.full_name);

            - name: Comment for internal PRs
              if: steps.commits.outputs.count < 2 && steps.commits.outputs.from_fork == 'false'
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.pull_request.number,
                        body: '❗ This pull request has fewer than 2 commits.\n\nYou can add an empty commit with the following command:\n\n```bash\ngit commit -m "Empty commit" --allow-empty\ngit push\n```\n\nPlease update the PR accordingly.'
                      });

            - name: Echo warning for external PRs
              if: steps.commits.outputs.count < 2 && steps.commits.outputs.from_fork == 'true'
              run: |
                  echo "⚠️ External PR detected with fewer than 2 commits. To add a commit, run: git commit -m \"Empty commit\" --allow-empty && git push."

            - name: Fail the job if fewer than 2 commits
              if: steps.commits.outputs.count < 2
              run: |
                  echo "❌ Failing the job because there are fewer than 2 commits."
                  exit 1
